### ISSUE TITLE
Group objectives to be displayed

### ISSUE THREAD

**Issue by yrm4foss** [fosstr/website#4]
The following objectives need to be displayed on our website:

"FOSSTR : Fostering Free and Open Source Software. 

The objectives of FOSSTR are: 
1. Education (Learn and Share) 
   1.1 to share the empowerment & freedoms that FOSS brings 
   1.2 to organise study-programs and events on various types of FOSS solutions 
2. Advocacy 
   2.1 encourage use of FOSS in organizations 
   2.2 encourage use of FOSS for personal use 
   2.3 encourage use of open standards for document exchange 
3. Contribution 
   3.1 active: code, patch, assist with localisation and documentation 
   3.2 passive: give feedback received from community to developers"

**Comment by indieNik** [comment]
Done! 
![screenshot 5](https://cloud.githubusercontent.com/assets/7264909/6545103/7ff6d288-c59b-11e4-9692-0c3ef6f7a219.png)

Working on the Layout and the Appearance now!

**Comment by SwAtm** [comment]
Suggestions:
1. Instead of 'We foster' - 'Fostering'
2. Instead of 'Our Objectives' - 'Objectives'

**Comment by indieNik** [comment]
Edited! Also revamped the site layout a bit!
![screenshot 8](https://cloud.githubusercontent.com/assets/7264909/6546705/868883b0-c5e3-11e4-85e4-5f3874ec4eb3.png)
