### ISSUE TITLE
Responsive website

### ISSUE THREAD

**Issue by gsama** [fosstr/website#5]
The website is responsive and works well. But there is a horizontal scroll still present for all sizes of window.
Tested on OSX 10.10.2 on Chrome 41.0.2272.89 and Safari 8.0.3
and Windows 7 on Firefox 35.0.1

This is a minor issue, but easy to fix now.

**Comment by indieNik** [comment]
The New Website is temporarily hosted on http://nikhilpatil.site88.net/
Does the issue still persist?

**Comment by gsama** [comment]
The issue is resolved. Thanks
