### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by gsama** [fosstr/website#8]
The Main menu of the website has FOSS, Wiki, and IRC.
Foss and Wiki are external links. I don't this this should in the Main Menu. This must go under links.

Then the next logical question will be - what should be in the main menu?

**Comment by digen** [comment]
Addressed in #6 Let me know your thoughts.

**Comment by digen** [comment]
FYI, the website displayed in the screenshot is currently not committed to the repo. After input from members will do the needful.
